name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - uses: actions/first-interaction@3c71ce730280171fd1cfb57c00c774f8998586f7 # v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Thank you for reporting an issue! If you haven't already [joined our Discord community](https://discord.com/invite/NetApp),
          then we invite you to do so. This is a great place to get help and ask questions from our community.
        pr-message: |
          Thank you for submitting a pull request! If you haven't already [joined our Discord community](https://discord.com/invite/NetApp),
          then we invite you to do so. It is a good place to discuss requests with the community.
